### PR TITLE
Deadlock fix: add informer callbacks before starting informers

### PR DESCRIPTION
**Pull request by khogeland**
For some reason, adding the callbacks after starting the informer causes a deadlock in `WaitForCacheSync`:

```
goroutine 1 [chan receive]:
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0003910a0, 0xc00058fb30, 0xc0000c20c0, 0x231e998, 0xc00058fb50)
	/home/khogeland/go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:330 +0x58
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/apimachinery/pkg/util/wait.PollUntil(0x5f5e100, 0xc00058fb30, 0xc0000c20c0, 0x43781f, 0xc00058fb20)
	/home/khogeland/go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:290 +0x56
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/client-go/tools/cache.WaitForCacheSync(0xc0000c20c0, 0xc00058fbb0, 0x1, 0x1, 0xc0000c20c0)
	/home/khogeland/go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:108 +0x7c
github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/controller/sparkapplication.(*Controller).Start(0xc000109050, 0xa, 0xc0000c20c0, 0xc00058fd68, 0x1)
	/home/khogeland/go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/controller/sparkapplication/controller.go:162 +0x161
main.main()
	/home/khogeland/go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/main.go:223 +0xa96
```

This reverts to the original ordering.

### CODE REVIEW

**Comment by liyinan926** [comment]
Interesting. We did start the informers before adding the callbacks before. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/v1beta1-0.9.0-2.4.0/main.go#L133.

**Comment by khogeland** [comment]
The callbacks are added in the NewController functions called above: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/v1beta1-0.9.0-2.4.0/main.go#L127-L130 
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/v1beta1-0.9.0-2.4.0/pkg/controller/sparkapplication/controller.go#L124

**Comment by liyinan926** [comment]
Ah, right.

**Comment by khogeland** [comment]
Possibly related, haven't read all the linked discussion: https://github.com/kubernetes/client-go/issues/382

**Pull request merged**
