### PR TITLE
[WIP] Refactor operator to use the controller runtime with multi-version support

### PR DESCRIPTION
**Pull request by skonto**
Aim is to solve #547. 
Important: _This a big refactoring and does not cover everything at the moment.  This is work in progress, goal is to get community feedback for moving forward with the refactoring.
Some important changes are: 
a) proper support for the status subresource
b) support for contr runtime 0.2.0 GA
c) support for logr -zap log
d) use the certification manager for injecting the webhook ca
e) use a hash to overcome the restriction that comes with the controller runtime about accessing previous state, as described here https://github.com/kubernetes-sigs/kubebuilder/issues/37#issuecomment-532281117. Predicates could be used but might be too much work.
f) go mod support
h) multi-namespace support
Note: crds require some work to become of `StructuralSchema` I noticed several violations when running `kubectl describe crd`. 
In order to test this:
```
$docker build --build-arg SPARK_IMAGE=gcr.io/spark-operator/spark:v2.4.4  -t skonto/operator:test -f Dockerfile .
#or use the following that requires to set GOPATH, go bin under PATH and GO111MODULE=on via export
$make docker-build SPARK-IMAGE=gcr.io/spark-operator/spark:v2.4.4 IMG=skonto/operator:test
$docker push skonto/operator:test
#setup minikube latest

$kubectl create namespace cert-manager
$kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true
$kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.10.1/cert-manager.yaml

# check in namespace cert-manager that all pods are running
# create crds
$kubectl apply -f manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
$kubectl apply -f manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
# create Spark operator pod, service etc
$kubectl apply -f all.yaml 
# check operator has started in namespace sparkoperator
# enable webhook service
$kubectl apply -f webhook.yaml

```
Run an application with the following spec spark-pi.yaml:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.4"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar"
  arguments:
    - "100"
  sparkVersion: "2.4.4"
  sparkConf: {}
  restartPolicy:
    type: Never
  driver:
    memory: "1g"
    labels:
      version: 2.4.4
    serviceAccount: spark-sa
    secrets:
      - name: mysecret
        path: /etc/config-secret
        secretType: generic
    configMaps:
      - name: myconfigmap
        path: /etc/config
  executor:
    instances: 2
    memory: "500m"
    labels:
      version: 2.4.4

```
To create the secrets use:
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: spark
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: myconfigmap
  namespace: spark
data:
  database: mysql
  database_uri: blablabla

```

```
#download file https://github.com/apache/spark/blob/master/resource-managers/kubernetes/integration-tests/dev/spark-rbac.yaml
$kubectl apply -f spark-rbac.yaml
$kubectl apply -f spark-pi.yaml
```
Log output of the operator can be found [here]https://gist.github.com/skonto/919a59d662b38fb4eb1dbc54d5765f72) for the app running to completion.

``` Status of spark-pi app
kubectl describe sparkapplications  -n spark
Name:         spark-pi
Namespace:    spark
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"sparkoperator.k8s.io/v1beta2","kind":"SparkApplication","metadata":{"annotations":{},"name":"spark-pi","namespace":"spark"}...
API Version:  sparkoperator.k8s.io/v1beta2
Kind:         SparkApplication
Metadata:
  Creation Timestamp:  2019-10-11T00:27:14Z
  Generation:          2
  Resource Version:    220909
  Self Link:           /apis/sparkoperator.k8s.io/v1beta2/namespaces/spark/sparkapplications/spark-pi
  UID:                 7d959c9a-acca-4764-baae-ce8fec588033
Spec:
  Arguments:
    100
  Driver:
    Config Maps:
      Name:  myconfigmap
      Path:  /etc/config
    Labels:
      Version:  2.4.4
    Memory:     1g
    Secrets:
      Name:           mysecret
      Path:           /etc/config-secret
      Secret Type:    generic
    Service Account:  spark-sa
  Executor:
    Instances:  2
    Labels:
      Version:            2.4.4
    Memory:               500m
  Image:                  lightbend/spark:2.1.2-OpenShift-2.4.4-rh-2.12
  Image Pull Policy:      Always
  Main Application File:  local:///opt/spark/examples/jars/spark-examples_2.12-2.1.2-2.4.4-lightbend.jar
  Main Class:             org.apache.spark.examples.SparkPi
  Mode:                   cluster
  Restart Policy:
    Type:  Never
  Spark Conf:
  Spark Version:  2.4.4
  Type:           Scala
Status:
  Apphash:  04f14ac0b65a58627350f019adcbe3b9a034d9adef34e47c5b21d42e14ea3d92
  Application State:
    State:  COMPLETED
  Driver Info:
    Pod Name:                    spark-pi-driver
    Web UI Address:              10.96.42.237:4040
    Web UI Port:                 4040
    Web UI Service Name:         spark-pi-ui-svc
  Execution Attempts:            1
  Last Submission Attempt Time:  2019-10-11T00:27:50Z
  Spark Application Id:          spark-f7789c37ae884e16832a478bb7cee04d
  Submission Attempts:           1
  Submission ID:                 0b4a134a-cd53-4a84-8622-218b5882cca4
  Termination Time:              <nil>
Events:
  Type     Reason                        Age                 From            Message
  ----     ------                        ----                ----            -------
  Normal   SparkApplicationAdded         2m                  spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
  Normal   SparkExecutorRunning          95s                 spark-operator  Executor spark-pi-1570753637441-exec-1 is running
  Normal   SparkExecutorRunning          95s                 spark-operator  Executor spark-pi-1570753637441-exec-2 is running
  Warning  SparkApplicationPendingRerun  92s                 spark-operator  SparkApplication spark-pi is pending rerun
  Normal   SparkApplicationSubmitted     84s (x2 over 112s)  spark-operator  SparkApplication spark-pi was submitted successfully
  Normal   SparkDriverRunning            79s (x2 over 108s)  spark-operator  Driver spark-pi-driver is running
  Normal   SparkDriverCompleted          65s                 spark-operator  Driver spark-pi-driver completed
  Normal   SparkApplicationCompleted     65s                 spark-operator  SparkApplication spark-pi completed

```
The following pass:
```
go vet ./...
go gmt ./...
go test ./...
```
just export GOPATH to be at your topdir, `export GO111MODULE=on` and add go binary to your path.
@liyinan926 pls review.

Most stuff has been migreated. 
Pending issues:
1) use the ctr runtime metrics (it is similar to what the operator implements right now but hides the details of having to setup your own http endpoint for metrics etc)
2) enable `resourceusage` capabilities
3) build sparkctl with make file
4) extend controller tests with the subJobManager details 
5) remove deps on crdclientset.
6) verify all functionality is working

### CODE REVIEW

**Comment by skonto** [comment]
@liyinan926 gentle ping.

**Comment by skonto** [comment]
thanks @liyinan926

**Comment by skonto** [comment]
@liyinan926 yes it needs testing I will try to finish all the functionality. How do you think we should proceed? Should we discuss this on slack?

**Comment by liyinan926** [comment]
@skonto if necessary, we can set up a quick Hangout meeting. Are you going to KubeCon next week? If so, we can also have a F2F meeting.

**Comment by skonto** [comment]
@liyinan926 sorry I missed the conversation here. I have now free time to revive the effort. Are you still available for a quick chat?

**Comment by skonto** [comment]
@liyinan926 gentle ping.

**Pull request closed without merging**
