### PR TITLE
Add configuration for SparkUI service type

### LINKED ISSUE #1096: Support configuring Service type for Spark UI
The Spark UI services are currently hardcoded to be ClusterIP types. Our Ingress controller requires services to be of type NodePort or LoadBalancer in order for our external load balancer to reach them. In order to support more Ingress implementations, the service type should be configurable.

### PR DESCRIPTION
**Pull request by jutley**
Fixes #1096. 

I also found that my controller-gen version behaved differently than the developer documentation described. I had to provide an additional configuration to use the v1beta1 CustomResourceDefinition version. I updated the docs and the generated CRDs accordingly.

### CODE REVIEW

**Comment by liyinan926** [comment]
Apparently this PR will revert some changes made in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1084. This is probably due to the version of controller-gen used.

**Comment by jkleckner** [comment]
And to expand on the previous comment, losing the protocol defaults from #1084 will make the chart not installable with k8s versions v1.18+

**Comment by jutley** [comment]
I'm struggling to understand how these CRDs are intended to be maintained. controller-gen generated the files in this PR (after I explicitly asked for the v1beta1 CRDs). This project is currently using v1.16 APIs, so I wouldn't necessarily expect the generation to gracefully handle v1.18 features.

It looks like #1084 manually updated the CRDs? This is just bad practice. The CRDs should either be generated or manually configured. Not both. I'll see if I can find a way to get the generated objects to include these fields.

**Comment by jutley** [comment]
Seems in the upstream library, `protocol` is documented as required, but annotated as optional.
https://github.com/kubernetes/kubernetes/blob/v1.19.4/pkg/apis/core/types.go#L1759-L1761

**Review by liyinan926 — APPROVED** [review]
LGTM.

**Comment by jkleckner** [comment]
@jutley Thank you for running this to ground.

**Comment by nssalian** [comment]
Has this been merged @liyinan926 ?
I don't see 
```
func getUIServiceType(app *v1beta2.SparkApplication) apiv1.ServiceType {
	if app.Spec.SparkUIOptions != nil && app.Spec.SparkUIOptions.ServiceType != nil {
		return *app.Spec.SparkUIOptions.ServiceType
	}
	return apiv1.ServiceTypeClusterIP
}
``` in the master branch.

**Pull request merged**
