### PR TITLE
Update who-is-using.md

### PR DESCRIPTION
**Pull request by Juandavi1**
We are using this great project in Siigo.com, it has worked very well and we would like to appear in the companies that use it.

### CODE REVIEW

**Comment by fgparamio** [comment]
> We are using this great project in Siigo.com, it has worked very well and we would like to appear in the companies that use it.

Totally true. It avoids us consuming unnecessary resources with other tools such as Databricks. The operation is perfect with 
spark-on-k8s-operator.  We broadcast about half a million kafka events in less than a second. Thank you very much Juanda

**Comment by liyinan926** [comment]
@Juandavi1 Thanks for the PR! Will merge once the CLA is signed.

**Comment by liyinan926** [comment]
@Juandavi1 if you are still willing to get this PR submitted, please sign the CLA so I can merge it. Thanks!

**Comment by Juandavi1** [comment]
Hi, 

the CLA has been submitted.

Thanks

**Pull request merged**
