### PR TITLE
[WIP] SparkApplicationClass CRD

### PR DESCRIPTION
**Pull request by eterna2**
This PR originated from #496 to support SparkUI service annotation so that ambassador ingress can be configured.

This PR proposed an additional of a new SparkApplicationClass  CRD:
> Kubernetes Operator for Apache Spark implements SparkApplication and ScheduledSparkApplication CustomResourceDefinitions (CRDs) to run or schedule spark applications in kubernetes (k8s). 
>
> SparkApplicationClass is a proposed k8s CRD to describe classes of spark applications which can be inherited by SparkApplication and ScheduledSparkApplication. This abstraction layer allows cluster administrators to declare a common set of spark application classes specific to their spark and k8s clusters, and/or their workload use cases. 

For full specification, see:
https://docs.google.com/document/d/1G9Kvi3ptf4mobrK2I5rPB_uAvFOymOLJsobuuPvCkS8/edit?usp=sharing

### CODE REVIEW

**Comment by eterna2** [comment]
Will rebase and sync this week and list out the parts that are still missing.

**Comment by liyinan926** [comment]
@eterna2 thanks for starting this!

**Comment by wackxu** [comment]
@eterna2 When will the code be ready? This is a great feature that we want to have a try.

**Comment by eterna2** [comment]
Hey @wackxu 

Thanks for the interest. I think will take awhile as I can only work on it for a few hours each week.

Because I just picked it up again, I need to do some refractoring again as there is quite Abit of change from beta1 to beta2 in how the crds are handled.

Feel free if you want to contribute?

**Comment by wackxu** [comment]
@eterna2 Yes, how can I start to help? you can assign some tasks to me.

**Comment by eterna2** [comment]
Hey @wackxu 

I have sent u an invite to my org: https://github.com/e2forks/spark-on-k8s-operator/invitations

Basically these are the brief overviews of what I have done, and needs to be done. We can discuss more:

DONE:
- rebase to recent master (I am picking it up, from a few months ago)

WIP:
- Shift the new CRD specification to `beta/v2` from `beta/v1` (i was working originally in `beta/v1` a few months ago. Now it is `beta/v2`)

TODO:
- Implement a deep merge method (sparkapplication -> sparkapplicationclass): essentially merge the sparkapplication spec attr into sparkapplicationclass template to return a new updated sparkapplication spec
- Update sparkapplication and scheduledsparkapplication controllers to check whether if a sparkapplicationclass is provided, if so, merge both spec to get the new sparkapplication spec
- Update `sparkui` method to create the new service/ingress based on the props declared in the new field `sparkUI`

**Pull request closed without merging**
