### PR TITLE
Fixed a bug that may lead to duplicated restarts when RestartPolicy=A…

### PR DESCRIPTION
**Pull request by bgeesaman**
…lways

### CODE REVIEW

**Comment by liyinan926** [comment]
@bgeesaman Please also include the changes in #160.

**Comment by dharmeshkakadia** [comment]
I hit duplicate drivers error today which looks like this. Here are the logs from launching. Interestingly enough, its launching drivers, even after I suspended the scheduledsparkapplication. 

```
I0712 17:55:23.231941       1 controller.go:550] SparkApplication braze-blob-delete-1531371618757426955 failed or terminated, restarting it with RestartPolicy OnFailure
I0712 17:55:23.404265       1 controller.go:550] SparkApplication braze-blob-delete-1531371618757426955 failed or terminated, restarting it with RestartPolicy OnFailure
I0712 17:55:23.409359       1 sparkui.go:74] Creating a service braze-blob-delete-1531371618757426955-2179596236-ui-svc for the Spark UI for application braze-blob-delete-1531371618757426955
I0712 17:55:23.423889       1 controller.go:550] SparkApplication braze-blob-delete-1531371618757426955 failed or terminated, restarting it with RestartPolicy OnFailure
I0712 17:55:23.469701       1 sparkui.go:74] Creating a service braze-blob-delete-1531371618757426955-4129467147-ui-svc for the Spark UI for application braze-blob-delete-1531371618757426955
I0712 17:55:23.469712       1 submission_runner.go:81] spark-submit arguments: [/opt/spark/bin/spark-submit --master k8s://https://10.0.0.1:443 --deploy-mode cluster --conf spark.kubernetes.namespace=default --conf spark.app.name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.container.image=mdldata.azurecr.io/data/gdpr-blob:latest --conf spark.eventLog.dir=wasb://events@sparkhistory.blob.core.windows.net/ --conf spark.eventLog.enabled=true --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-id=braze-blob-delete-1531371618757426955-2179596236 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.driver.cores=2.000000 --conf spark.driver.memory=2048m --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark --conf spark.kubernetes.driver.label.version=2.4.0 --conf spark.kubernetes.driver.secrets.mdldatasecrets-gdpr-blob=/mnt/secrets/ --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-id=braze-blob-delete-1531371618757426955-2179596236 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.executor.instances=20 --conf spark.executor.cores=2 --conf spark.executor.memory=4096m --conf spark.kubernetes.executor.label.version=2.4.0 --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGiVicmF6ZS1ibG9iLWRlbGV0ZS0xNTMxMzcxNjE4NzU3NDI2OTU1IiQ3OTBlYWEwOS04NTkwLTExZTgtOWI5OC0wYTU4YWMxZjBhMDQqHXNwYXJrb3BlcmF0b3IuazhzLmlvL3YxYWxwaGEx local:///code/delete_controller_braze.py]
I0712 17:55:23.689973       1 sparkui.go:74] Creating a service braze-blob-delete-1531371618757426955-3259651411-ui-svc for the Spark UI for application braze-blob-delete-1531371618757426955
I0712 17:55:23.690055       1 submission_runner.go:81] spark-submit arguments: [/opt/spark/bin/spark-submit --master k8s://https://10.0.0.1:443 --deploy-mode cluster --conf spark.kubernetes.namespace=default --conf spark.app.name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.container.image=mdldata.azurecr.io/data/gdpr-blob:latest --conf spark.eventLog.dir=wasb://events@sparkhistory.blob.core.windows.net/ --conf spark.eventLog.enabled=true --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-id=braze-blob-delete-1531371618757426955-4129467147 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.driver.cores=2.000000 --conf spark.driver.memory=2048m --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark --conf spark.kubernetes.driver.label.version=2.4.0 --conf spark.kubernetes.driver.secrets.mdldatasecrets-gdpr-blob=/mnt/secrets/ --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-id=braze-blob-delete-1531371618757426955-4129467147 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.executor.instances=20 --conf spark.executor.cores=2 --conf spark.executor.memory=4096m --conf spark.kubernetes.executor.label.version=2.4.0 --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGiVicmF6ZS1ibG9iLWRlbGV0ZS0xNTMxMzcxNjE4NzU3NDI2OTU1IiQ3OTBlYWEwOS04NTkwLTExZTgtOWI5OC0wYTU4YWMxZjBhMDQqHXNwYXJrb3BlcmF0b3IuazhzLmlvL3YxYWxwaGEx local:///code/delete_controller_braze.py]
I0712 17:55:23.709358       1 submission_runner.go:99] spark-submit completed for SparkApplication braze-blob-delete-1531371618757426955 in namespace default
I0712 17:55:24.409138       1 submission_runner.go:81] spark-submit arguments: [/opt/spark/bin/spark-submit --master k8s://https://10.0.0.1:443 --deploy-mode cluster --conf spark.kubernetes.namespace=default --conf spark.app.name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.container.image=mdldata.azurecr.io/data/gdpr-blob:latest --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=wasb://events@sparkhistory.blob.core.windows.net/ --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-id=braze-blob-delete-1531371618757426955-3259651411 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.driver.cores=2.000000 --conf spark.driver.memory=2048m --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark --conf spark.kubernetes.driver.label.version=2.4.0 --conf spark.kubernetes.driver.secrets.mdldatasecrets-gdpr-blob=/mnt/secrets/ --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=braze-blob-delete-1531371618757426955 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-id=braze-blob-delete-1531371618757426955-3259651411 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.executor.instances=20 --conf spark.executor.cores=2 --conf spark.executor.memory=4096m --conf spark.kubernetes.executor.label.version=2.4.0 --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGiVicmF6ZS1ibG9iLWRlbGV0ZS0xNTMxMzcxNjE4NzU3NDI2OTU1IiQ3OTBlYWEwOS04NTkwLTExZTgtOWI5OC0wYTU4YWMxZjBhMDQqHXNwYXJrb3BlcmF0b3IuazhzLmlvL3YxYWxwaGEx local:///code/delete_controller_braze.py]
I0712 17:56:10.112286       1 submission_runner.go:99] spark-submit completed for SparkApplication braze-blob-delete-1531371618757426955 in namespace default
I0712 17:56:16.214237       1 submission_runner.go:99] spark-submit completed for SparkApplication braze-blob-delete-1531371618757426955 in namespace default
```

**Comment by liyinan926** [comment]
PR https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/206https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/206 should fix the bug. @dharmeshkakadia can you try the latest master? BTW: if you are using `ScheduledSparkApplication`, it's recommended to use a RestartPolicy of `Never` as documented [here](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#running-spark-applications-on-a-schedule-using-a-scheduledsparkapplication).

**Comment by dharmeshkakadia** [comment]
Oh I missed that. I am using the `OnFailure` policy. I would actually want the job to be retried immediately and not wait for the next run. For example, some jobs have a bi-weekly schedule. I wold want it to be retried on failure and not wait for ~1 month between two successful runs. Thoughts?

**Comment by liyinan926** [comment]
I would recommend giving the latest master a try with the current RestartPolicy you are using.

**Comment by dharmeshkakadia** [comment]
Cool. Let me try that. Also, it seems in my current scenario, `maxSubmissionRetries` also might not be honored. Have you seen this before?

**Comment by liyinan926** [comment]
No, I haven't seen that before.

**Comment by liyinan926** [comment]
Were you building the operator binary on your local laptop?

**Comment by dharmeshkakadia** [comment]
Yes. I had been doing this before as well. Did something change? Is it not recommend ?

**Comment by liyinan926** [comment]
You will need to add `GOOS=linux` to your `go build` command.

**Comment by dharmeshkakadia** [comment]
This is what I did `docker build -f Dockerfile -t dharmeshkakadia/spark-operator .` only change in the dockerfile is using `dharmeshkakadia/spark-py-ubuntu` image instead of `gcr.io/ynli-k8s/spark:v2.3.0`. Where are you suggesting I add `GOOS=linux` ?

**Comment by yuchaoran2011** [comment]
@dharmeshkakadia I've seen a similar error before. Look at this [issue](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/191).

**Comment by liyinan926** [comment]
@yuchaoran2011 The build process has changed. The docker build process now includes a build of the operator binary. This is far better than building locally and copying the binary into the image as it gives a consistent build regardless where you build the image.

**Comment by dharmeshkakadia** [comment]
I am actually using docker build for building the image. I misunderstood the "running on laptop" question. But it looks suspiciously similar to your link.

**Comment by yuchaoran2011** [comment]
Ok thanks for the clarifications!

**Comment by dharmeshkakadia** [comment]
FYI : this is issue when spark image and operator image are different. Here is the fix : https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/210

**Comment by liyinan926** [comment]
The relevant changes have already been merged back to the 2.2 branch.

**Pull request closed without merging**
