### PR TITLE
Added support for --packages

### PR DESCRIPTION
**Pull request by liyinan926**

### CODE REVIEW

**Comment by skonto** [comment]
@liyinan926 I am planning to fix it in cluster mode for the spark backend. I need for the RSS stuff.

**Comment by liyinan926** [comment]
Thanks @skonto.

**Comment by redsk** [comment]
Hi guys, out of curiosity, why is this PR on hold? It would be a very useful feature! Cheers.

**Comment by liyinan926** [comment]
@redsk because `--package` support for the Kubernetes mode won't be available until Spark 3.0 gets released. You can certainly use the Spark master to try it out, but we will hold on merging this until it's official released.

**Pull request closed without merging**
