### PR TITLE
Updated to use the v1beta1 APIs and project status to beta

### PR DESCRIPTION
**Pull request by liyinan926**

### CODE REVIEW

**Comment by akhurana001** [comment]
@liyinan926 https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/291 breaks backward compatibility for the CRD. Can we please wait to close out on those changes before merging this in ?  Thanks.

**Comment by liyinan926** [comment]
@akhurana001 sure, this is not urgent.

**Comment by yuchaoran2011** [comment]
Hi @liyinan926 Is this PR good to be merged? If so can you do it?

**Comment by liyinan926** [comment]
This one is deprecated. I will create a new one.

**Pull request closed without merging**
