### PR TITLE
[WIP] Refactor operator to use the controller runtime

### PR DESCRIPTION
**Pull request by skonto**
Aim is to solve #547. 
Important: _This a big refactoring and does not cover everything at the moment. Leader election, scheduled apps and the Volcano support are disabled._ This is work in progress, goal is to get community feedback for moving forward with the refactoring.
Some important changes are: 
a) proper support for the status subresource
b) support for contr runtime 0.2.0 GA
c) support for logr -zap log
d) use the certification manager for injecting the webhook ca
e) use a hash to overcome the restriction that comes with the controller runtime about accessing previous state, as described here https://github.com/kubernetes-sigs/kubebuilder/issues/37#issuecomment-532281117. Predicates could be used but might be too much work.
f) go mod support
Note: crds require some work to become of `StructuralSchema` I noticed several violations when running `kubectl describe crd`. 
In order to test this:
```
$docker build --build-arg SPARK_IMAGE=gcr.io/spark-operator/spark:v2.4.4  -t skonto/operator:test -f Dockerfile .
#or use the following that requires to set GOPATH, go bin under PATH and GO111MODULE=on via export
$make docker-build SPARK-IMAGE=gcr.io/spark-operator/spark:v2.4.4 IMG=skonto/operator:test
$docker push skonto/operator:test
#setup minikube latest

$kubectl create namespace cert-manager
$kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true
$kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.10.1/cert-manager.yaml

# check in namespace cert-manager that all pods are running
# create crds
$kubectl apply -f manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
$kubectl apply -f manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
# create Spark operator pod, service etc
$kubectl apply -f all.yaml 
# check operator has started in namespace sparkoperator
# enable webhook service
$kubectl apply -f webhook.yaml

```
Run an application with the following spec spark-pi.yaml:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.4"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar"
  arguments:
    - "100"
  sparkVersion: "2.4.4"
  sparkConf: {}
  restartPolicy:
    type: Never
  driver:
    memory: "500m"
    labels:
      version: 2.4.4
    serviceAccount: spark-sa
    secrets:
      - name: mysecret
        path: /etc/config-secret
        secretType: generic
    configMaps:
      - name: myconfigmap
        path: /etc/config
  executor:
    instances: 2
    memory: "500m"
    labels:
      version: 2.4.4

```
To create the secrets use:
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: spark
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: myconfigmap
  namespace: spark
data:
  database: mysql
  database_uri: blablabla

```

```
#download file https://github.com/apache/spark/blob/master/resource-managers/kubernetes/integration-tests/dev/spark-rbac.yaml
$kubectl apply -f spark-rbac.yaml
$kubectl apply -f spark-pi.yaml
```
Log output of the operator can be found [here](https://gist.github.com/skonto/38ce04c029d2a3297f206990822d88fc) for the app running to completion.

``` Status of spark-pi app
kubectl describe sparkapplications -n spark
Name:         spark-pi
Namespace:    spark
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"sparkoperator.k8s.io/v1beta2","kind":"SparkApplication","metadata":{"annotations":{},"name":"spark-pi","namespace":"spark"}...
API Version:  sparkoperator.k8s.io/v1beta2
Kind:         SparkApplication
Metadata:
  Creation Timestamp:  2019-09-30T00:59:22Z
  Generation:          1
  Resource Version:    1335
  Self Link:           /apis/sparkoperator.k8s.io/v1beta2/namespaces/spark/sparkapplications/spark-pi
  UID:                 d19b28af-7e48-4426-b805-5161ac5b4cd2
Spec:
  Arguments:
    100
  Driver:
    Config Maps:
      Name:  myconfigmap
      Path:  /etc/config
    Labels:
      Version:  2.4.4
    Memory:     500m
    Secrets:
      Name:           mysecret
      Path:           /etc/config-secret
      Secret Type:    generic
    Service Account:  spark-sa
  Executor:
    Instances:  2
    Labels:
      Version:            2.4.4
    Memory:               500m
  Image:                  gcr.io/spark-operator/spark:v2.4.4
  Image Pull Policy:      Always
  Main Application File:  local:///opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar
  Main Class:             org.apache.spark.examples.SparkPi
  Mode:                   cluster
  Restart Policy:
    Type:  Never
  Spark Conf:
  Spark Version:  2.4.4
  Type:           Scala
Status:
  Apphash:  cc6a6c6866c7d67f763b633015903ea7594b5f044bfbde7f8d3e0377c45534fd
  Application State:
    State:  COMPLETED
  Driver Info:
    Pod Name:                    spark-pi-driver
    Web UI Address:              10.98.211.121:4040
    Web UI Port:                 4040
    Web UI Service Name:         spark-pi-ui-svc
  Execution Attempts:            1
  Last Submission Attempt Time:  2019-09-30T00:59:30Z
  Spark Application Id:          spark-94c375a44ad74291b55ae973fcc20e4d
  Submission Attempts:           1
  Submission ID:                 73cc8356-fd83-420f-9694-25a24a6bd4d5
  Termination Time:              <nil>
Events:
  Type    Reason                     Age   From            Message
  ----    ------                     ----  ----            -------
  Normal  SparkApplicationAdded      41s   spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
  Normal  SparkApplicationSubmitted  33s   spark-operator  SparkApplication spark-pi was submitted successfully
  Normal  SparkDriverRunning         30s   spark-operator  Driver spark-pi-driver is running
  Normal  SparkDriverCompleted       17s   spark-operator  Driver spark-pi-driver completed
  Normal  SparkApplicationCompleted  17s   spark-operator  SparkApplication spark-pi completed
```
The following pass:
```
go vet ./...
go gmt ./...
go test ./...
```
just export GOPATH to be at your topdir, `export GO111MODULE=on` and add go binary to your path.
@liyinan926 pls review and let me know how you want me to proceed with this effort.
Usually a big refactoring like this, requires at some point to stop getting new PRs in
otherwise its hard to keep-up with all the changes happening.

### CODE REVIEW

**Comment by liyinan926** [comment]
@skonto thank you for this PR! Highly appreciate it. Just want to let you know that we have discussed and planned to address #610 and make the changes in branch `multi-version-support` part of `v1beta3` next. I suggest you base this PR on the `multi-version-support` branch instead of the master. This will make our life easier merging both sets of changes.

**Comment by skonto** [comment]
@liyinan926 ok sure I will do that might close this one and create a new one will see thanks!

**Comment by liyinan926** [comment]
@skonto Thanks!

**Comment by skonto** [comment]
closing this in favor of https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/658

**Pull request closed without merging**
