### PR TITLE
Re-enable e2e integration tests and fix small issue with deleting SparkApplication

### PR DESCRIPTION
**Pull request by aneagoe**
This PR fixes the following issues:
* https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1416
* https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1467

It also bumps the chart version and spark-operator version. 

The e2e integration tests have been broken for a while now. This change only fixes the issues and re-enables them; however nothing is changed about the tests themselves. I've noticed that upon many runs there are some occasional failures, perhaps due to some race-conditions:
```
| cleaning up caches and output
| running unit tests
| === RUN   TestSubmitSparkPiYaml
| === PAUSE TestSubmitSparkPiYaml
| === RUN   TestSubmitSparkPiCustomResourceYaml
| === PAUSE TestSubmitSparkPiCustomResourceYaml
| === RUN   TestLifeCycleManagement
| --- PASS: TestLifeCycleManagement (73.16s)
| === RUN   TestMountConfigMap
| --- PASS: TestMountConfigMap (7.09s)
| === CONT  TestSubmitSparkPiYaml
| === CONT  TestSubmitSparkPiCustomResourceYaml
| --- PASS: TestSubmitSparkPiCustomResourceYaml (38.10s)
| === CONT  TestSubmitSparkPiYaml
|     basic_test.go:63:
|         	Error Trace:	basic_test.go:63
|         	Error:      	Not equal:
|         	            	expected: <nil>(<nil>)
|         	            	actual  : *errors.errorString(&errors.errorString{s:"timed out waiting for the condition"})
|         	Test:       	TestSubmitSparkPiYaml
|     basic_test.go:68:
|         	Error Trace:	basic_test.go:68
|         	Error:      	Not equal:
|         	            	expected: <nil>(<nil>)
|         	            	actual  : *errors.errorString(&errors.errorString{s:"resource name may not be empty"})
|         	Test:       	TestSubmitSparkPiYaml
|     basic_test.go:69:
|         	Error Trace:	basic_test.go:69
|         	Error:      	Should not be: -1
|         	Test:       	TestSubmitSparkPiYaml
| --- FAIL: TestSubmitSparkPiYaml (240.09s)
| FAIL
| FAIL	github.com/GoogleCloudPlatform/spark-on-k8s-operator/test/e2e	325.659s
| FAIL
| make: *** [Makefile:74: integration-test] Error 1
```

@TomHellier a review of the changes around e2e tests would be greatly appreciated. All my local tests were done against minikube with either [act](https://github.com/nektos/act) or just manual run (`make integration-test`).

### CODE REVIEW

**Comment by TomHellier** [comment]
Thanks for this PR, I think @liyinan926 is only person able to merge, I have the ability to run tests on my prs for some reason so I hope he gives ability for your prs to use ci.

I've added a few comments

**Comment by cwyl02** [comment]
hey @aneagoe could you please retry on the failed integration test? It would be really nice if this can be merged soon since I have a project depends on this. cc @liyinan926

**Comment by aneagoe** [comment]
@cwyl02 unfortunately I don't have the necessary permissions to trigger a re-run of the integration test.

**Comment by TomHellier** [comment]
@liyinan926 is it possible to get more maintainers for this project, even if limited permissions it will help community maintain this repo

**Comment by aneagoe** [comment]
I've tried force pushing but it had no effect. As well, the aim of this PR is to enable the check as they were previously defined, not necessarily fixing any race conditions. My hope is that the checks can be refined at a later stage once we gain more insight into what works and what not. From my local testing, I did notice that repeating the integration tests time and time again, there were timeouts or race conditions in about 40% of the cases.

**Comment by aneagoe** [comment]
I will split this up and refactor it.

**Pull request closed without merging**
