### PR TITLE
Add Operator volumes and volumeMounts in chart

### PR DESCRIPTION
**Pull request by ocworld**
It is needed to mount one or more volumes into spark operator pod  because of various reasons such as external ivy cache.

In this pr, it is supported to operator pod's volumes and volumeMounts in chart.

### CODE REVIEW

**Comment by ocworld** [comment]
@ahnlab-oss

**Comment by liyinan926** [comment]
Please update the chart version.

**Comment by ocworld** [comment]
> Please update the chart version.

chart version is updated to 1.1.18

**Comment by liyinan926** [comment]
Looks like you need to bump the Chart version again due to conflict.

**Comment by liyinan926** [comment]
Looks like chart fails to build due to the following error. So you need to fix the linting.

```
Error: Error linting charts: Error processing charts
```

**Comment by ocworld** [comment]
> Looks like chart fails to build due to the following error. So you need to fix the linting.
> 
> ```
> Error: Error linting charts: Error processing charts
> ```

It is fixed

**Pull request merged**
