### PR TITLE
Some minor tweaks around handling of reruns

### PR DESCRIPTION
**Pull request by liyinan926**

### CODE REVIEW

**Comment by skonto** [comment]
@liyinan926 we just faced an issue where after a pod update resources were not removed and so the re-submission caused a resource conflict because the pod name is deterministic.

**Comment by liyinan926** [comment]
OK, so you meant the check for deletion of app resources is necessary, right?

**Comment by skonto** [comment]
Yes it is required but will verify what happened from the log.

**Comment by skonto** [comment]
@liyinan926 from what I see from the logs the deletion never happened:
```
I0315 12:48:46.440814      12 webhook.go:120] Serving admission request
W0315 12:48:46.687761      12 submission.go:72] trying to resubmit an already submitted SparkApplication spark-resilience-test/spark-resilience-test-rs-ingress
I0315 12:48:46.687813      12 controller.go:509] Trying to update SparkApplication spark-resilience-test/spark-resilience-test-rs-ingress, from: [{ 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {PENDING_RERUN } map[] 0 0}] to [{ 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {PENDING_RERUN } map[] 0 0}]
I0315 12:48:46.688143      12 controller.go:254] Ending processing key: "spark-resilience-test/spark-resilience-test-rs-ingress"
I0315 12:48:46.688264      12 controller.go:247] Starting processing key: "spark-resilience-test/spark-resilience-test-rs-ingress"
I0315 12:48:46.688343      12 controller.go:509] Trying to update SparkApplication spark-resilience-test/spark-resilience-test-rs-ingress, from: [{ 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {INVALIDATING } map[] 0 0}] to [{ 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {PENDING_RERUN } map[] 0 0}]
I0315 12:48:46.697213      12 sparkapp_metrics.go:135] Exporting metrics for spark-resilience-test-rs-ingress; old status: { 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {INVALIDATING } map[] 0 0} new status: { 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {PENDING_RERUN } map[] 0 0}
I0315 12:48:46.697278      12 controller.go:254] Ending processing key: "spark-resilience-test/spark-resilience-test-rs-ingress"
I0315 12:48:46.697758      12 controller.go:207] SparkApplication spark-resilience-test/spark-resilience-test-rs-ingress was updated, enqueueing it
I0315 12:48:46.697824      12 controller.go:247] Starting processing key: "spark-resilience-test/spark-resilience-test-rs-ingress"
```

**Comment by liyinan926** [comment]
Closing this PR.

**Pull request closed without merging**
