### PR TITLE
Add spark-operator chart

### PR DESCRIPTION
**Pull request by HagaiBarel**
Related to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1021

### CODE REVIEW

**Comment by scravy** [comment]
This fails on Kubernetes > 1.13 due to

```
Error: chart requires kubeVersion: >= 1.13.x which is incompatible with Kubernetes v1.18.8-eks-7c9bda
```

The `kubeVersion` mentioned is `>= 1.13.x` which limits it to `< 1.14`. See also https://helm.sh/docs/topics/charts/#the-kubeversion-field

**Comment by scravy** [comment]
I removed the `kubeVersion` and getting this now:

```
Release "spark-operator" does not exist. Installing it now.

Error: failed to install CRD crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml: CustomResourceDefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
```

**Comment by HagaiBarel** [comment]
> I removed the `kubeVersion` and getting this now:
> 
> ```
> Release "spark-operator" does not exist. Installing it now.
> 
> Error: failed to install CRD crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml: CustomResourceDefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
> ```

Seems like an issue with CRD changes intoduced in `1.18`, I think this is the issue https://github.com/kubernetes/kubernetes/issues/91395, didn't see it before as I was testing on versions `1.16` and `1.17`

Pinging @yuchaoran2011 @liyinan926

**Review by liyinan926 — APPROVED** [review]
LGTM. Thanks for adding the chart!

**Comment by scravy** [comment]
From which repo will we be able to install this chart?

**Comment by jkleckner** [comment]
The current most recent commit [1] still advises to use the deprecated [2] repo source.

If I fetch the chart it is the old one.  What am I missing?

[1] https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/98414e7c3b42c83b29cfe3ae936adc40d900af5a

[2] https://charts.helm.sh/incubator/ and follow the status or deprecation links.

**Comment by jgardner04** [comment]
@jkleckner the action is in place but the gh-pages branch needs to be created by a contributor. This will enable the creation of an index.yaml file in that branch that will allow you to add it as a source in Helm 3. I do have this working on [my fork](https://github.com/jgardner04/spark-on-k8s-operator) if you are in a bind and need to use it to deploy. You would use http://beyondthecorneroffice.com/spark-on-k8s-operator as your repo.

**Comment by jkleckner** [comment]
@jgardner04 Thank you.

It turns out you can use a local file path for the chart as well, which I got working.  We are also going to bundle this chart into our own chart museum.

As a side-effect, I noticed that current kubernetes v1.9.x requires some patches as seen in [1].

So I created a PR #1084 for this repo [2] that brings those changes back here.

[1] https://github.com/kudobuilder/operators/pull/297

[2] https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1084

**Comment by jkleckner** [comment]
> > I removed the `kubeVersion` and getting this now:
> > ```
> > Release "spark-operator" does not exist. Installing it now.
> > 
> > Error: failed to install CRD crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml: CustomResourceDefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
> > ```
> 
> Seems like an issue with CRD changes intoduced in `1.18`, I think this is the issue [kubernetes/kubernetes#91395](https://github.com/kubernetes/kubernetes/issues/91395), didn't see it before as I was testing on versions `1.16` and `1.17`
> 
> Pinging @yuchaoran2011 @liyinan926

@HagaiBarel This should be fixed with #1084

**Comment by jkleckner** [comment]
@HagaiBarel   have you tried tolerations at all?

I'm finding that `nodeSelector` and `tolerations` don't work declared in the executor spec.

The `nodeSelector` works if put directly in  the `spec` *and* if the label is fully qualified with `kubernetes.io/` as for example `kubernetes.io/hostname: "docker-desktop"` but tolerations don't work even with trying out various paths.

I'll file an issue.

**Pull request merged**
